version: "3"
services:
  personnel:
    environment:
      TZ: Europe/Oslo
    image: dtr.fintlabs.no/beta/fake-personnel-adapter
  student:
    environment:
      TZ: Europe/Oslo
    image: dtr.fintlabs.no/beta/fake-student-adapter
