security:
 basic:
  enabled: false

fint:
 adapter:
  organizations: mock.no
  endpoints:
   providers:
    personal: http://localhost:8081/provider
  fake:
   employees: 100000

 oauth:
  enabled: false

